apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-thesis
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATASOURCE_URL: "postgresql://${db_username}:${db_password}@postgres-headless.my-thesis.svc.cluster.local:5432/${db_name}?sslmode=disable"
  ROLE_ADMIN_CODE: "1"
  ROLE_TEACHER_CODE: "2"
  ROLE_STUDENT_CODE: "3"
  CLIENT_ORIGIN: "http://34.92.62.138/app"
  NEXT_PUBLIC_GRAPHQL_URI: "http://34.92.62.138/api/graphql"
  BACKEND_URL: "http://34.92.62.138/api/graphql"
  NODE_ENV: "production"
  COOKIE_DOMAIN: "34.92.62.138"
  HTTPS_ENABLED: "false"

  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "rabbit-user"
  RABBITMQ_PASSWORD: "S3cur3P@ssw0rd123!"
  RABBITMQ_URL: "amqp://rabbit-user:S3cur3P@ssw0rd123!@rabbitmq:5672"

  # Database Configuration for LLM
  DB_HOST: "postgres-llm"
  DB_PORT: "5432"
  DB_NAME: "grading_service"
  DB_USER: "grading_user"
  DB_PASSWORD: "grading_password"
  DATASOURCE_URL: "postgresql://${db_username}:${db_password}@postgres-headless.my-thesis.svc.cluster.local:5432/${db_name}?sslmode=disable"
