apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-thesis
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATASOURCE_URL: "postgresql://${db_username}:${db_password}@postgres-headless.my-thesis.svc.cluster.local:5432/${db_name}?sslmode=disable"
  ROLE_ADMIN_CODE: "1"
  ROLE_TEACHER_CODE: "2"
  ROLE_STUDENT_CODE: "3"
  CLIENT_ORIGIN: "http://${ingress_ip}/app"
  NEXT_PUBLIC_GRAPHQL_URI: "http://${ingress_ip}/api/graphql"
  BACKEND_URL: "http://${ingress_ip}/api/graphql"
