apiVersion: v1
kind: Secret
metadata:
  name: github-fe-repo-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:tpSpace/thesis-fe.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDdElxOzOERVIM8yX+eGeOhF9IxBdT+knv47bIGPoLRegAAAJhv8k7qb/JO
    6gAAAAtzc2gtZWQyNTUxOQAAACDdElxOzOERVIM8yX+eGeOhF9IxBdT+knv47bIGPoLReg
    AAAEAu9Ox879slSJMA7fdsT378apxcHc7neiTglTk7rXVxIt0SXE7M4RFUgzzJf54Z46EX
    0jEF1P6Se/jtsgY+gtF6AAAAEGFyZ29jZC1mZS1hY2Nlc3MBAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  revision: main
