apiVersion: v1
kind: Secret
metadata:
  name: github-llm-repo-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:tpSpace/thesis-grading.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAauaeUqsSs1K7BXBhzaR+d0KaIqhugHFb0CZfXAcJ6swAAAKAqT6LRKk+i
    0QAAAAtzc2gtZWQyNTUxOQAAACAauaeUqsSs1K7BXBhzaR+d0KaIqhugHFb0CZfXAcJ6sw
    AAAEBpmM98Ub82+TxfAdI26mY8lXWjvq1XgbryH822NJCZiBq5p5SqxKzUrsFcGHNpH53Q
    poiqG6AcVvQJl9cBwnqzAAAAHGFyZ29jZC10aGVzaXMtZ3JhZGluZy1hY2Nlc3MB
    -----END OPENSSH PRIVATE KEY-----
  revision: main
