apiVersion: v1
kind: Secret
metadata:
  name: github-repo-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:tpSpace/infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----

    -----END OPENSSH PRIVATE KEY-----
  revision: master
