apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thesis-frontend
  namespace: argocd
spec:
  project: thesis
  source:
    repoURL: https://github.com/tpSpace/infra.git
    targetRevision: HEAD
    path: fe
  destination:
    server: https://kubernetes.default.svc
    namespace: my-thesis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
